version: '3'
services:
  website:
    build: .
    restart: unless-stopped
    ports:
      - '8081:8081'
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: 'website'
      MYSQL_DATABASE: 'website'
      MYSQL_USER: 'website'
      MYSQL_PASSWORD: 'uHVy93yhwUKrsoKpALwnDSzb8sYMGBBr'
    volumes:
      - ./data:/var/lib/mysql
