name: first-github-action
on: [push]
jobs:
  write-to-console:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello Wordl!'
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses:  shimataro/ssh-key-action@v2
        with:
          key: ${{secrets.CONTABO_SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder'
      - name: Adding Known Host
        run: ssh-keyscan -H ${{ secrets.CONTABO_HOST }} >> ~/.ssh/known_hosts
      - name: Connect
        run: ssh root@${{ secrets.CONTABO_HOST }}
        run: ls
        
