name: first-github-action
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello Wordl!'
  
  develop:
    name: Develop
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CONTABO_HOST }}
          username: root
          key: ${{ secrets.CONTABO_SSH_PRIVATE_KEY}}
          port: 22
          script: |
            ls -al

  live:
    name: Live
    environment: Live
    runs-on: ubuntu-latest
    needs: develop
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CONTABO_HOST }}
          username: root
          key: ${{ secrets.CONTABO_SSH_PRIVATE_KEY}}
          port: 22
          script: |
            ls -al
